import { getAssignmentStatusLabel } from "@/lib/assignment-status"
import { normalizeAssignmentType } from "@/lib/assignment-types"
import type { Assignment, DashboardFilterPreferences } from "@/types"
export type DashboardQuickView = "all" | "attention" | "ongoing" | "completed"
export type DashboardSortField = "deadline" | "name"
export type DashboardSortDirection = "asc" | "desc"
export function localDeadline(value: Pick<Assignment, "dueDate" | "dueTime">) { if (!value.dueDate) return null; const [y,m,d]=value.dueDate.split("-").map(Number); const [h=0,min=0]=value.dueTime?.split(":").map(Number) ?? []; return new Date(y,m-1,d,h,min) }
function dayStart(date: Date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate()) }
export function isDashboardOverdue(a: Assignment, now = new Date()) { const due=localDeadline(a); return a.status!=="completed" && Boolean(due && dayStart(due!) < dayStart(now)) }
export function isDashboardDueSoon(a: Assignment, now = new Date()) { const due=localDeadline(a); if (a.status==="completed" || !due) return false; const delta=(dayStart(due).getTime()-dayStart(now).getTime())/86400000; return delta>=0 && delta<=7 }
export function dashboardCounts(items: Assignment[], now = new Date()) { return { overdue: items.filter(a=>isDashboardOverdue(a,now)).length, dueSoon: items.filter(a=>isDashboardDueSoon(a,now)).length, ongoing: items.filter(a=>a.status==="ongoing").length, completed: items.filter(a=>a.status==="completed").length } }
function matches(a: Assignment, filters: DashboardFilterPreferences, query: string, quick: DashboardQuickView, now: Date) { const q=query.trim().toLowerCase(); const search=!q || [a.title,normalizeAssignmentType(a.category),a.priority,getAssignmentStatusLabel(a.status),a.assigneeName,a.assigneeEmail,a.notes].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)); const filter=(filters.type==="all"||normalizeAssignmentType(a.category)===filters.type)&&(filters.priority==="all"||a.priority===filters.priority)&&(filters.status==="all"||a.status===filters.status); const view=quick==="all"||(quick==="completed"&&a.status==="completed")||(quick==="ongoing"&&a.status==="ongoing")||(quick==="attention"&&(isDashboardOverdue(a,now)||isDashboardDueSoon(a,now))); return search&&filter&&view }
export function deriveDashboardView(items: Assignment[], options: { filters: DashboardFilterPreferences; query: string; quickView: DashboardQuickView; sortField: DashboardSortField; sortDirection: DashboardSortDirection; now?: Date }) { const now=options.now??new Date(); const indexed=items.map((a,index)=>({a,index})).filter(({a})=>matches(a,options.filters,options.query,options.quickView,now)); const dir=options.sortDirection==="asc"?1:-1; indexed.sort((x,y)=>{ if ((x.a.status==="completed") !== (y.a.status==="completed")) return x.a.status==="completed"?1:-1; let result=0; if(options.sortField==="name") result=x.a.title.localeCompare(y.a.title,undefined,{sensitivity:"base"}); else { const ax=localDeadline(x.a)?.getTime()??Number.MAX_SAFE_INTEGER; const ay=localDeadline(y.a)?.getTime()??Number.MAX_SAFE_INTEGER; result=ax-ay } return result ? result*dir : x.index-y.index }); const all=indexed.map(x=>x.a); return { incomplete: all.filter(a=>a.status!=="completed"), completed: all.filter(a=>a.status==="completed"), all } }
